### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by THEYASHGAUR** [SiddharthDubey52/jonny-trojan#1]
there is a bug in this repo.....just joking bro
dekh rha hu bsss ki new issue kaise report krte h 
pta nhi ye issue tere pass pochega bhi ya nhi 😂😂😂

**Comment by SiddharthDubey52** [comment]
Pohoch gya bhai

**Comment by THEYASHGAUR** [comment]
Ok thanks 🙏🙇👻
